name: DC_main_randn
version: 0.1

training:
  # train_lambda: 1024
  # q_index: 2

  base_lr: 0.0002

  batch_size: 3

  flow_pretrain_dir: ../../flow/


  multi_frame_training: false

  # for single frame training
  stage_milestones: [10, 25, 40]
  lr_milestones: [50, 55, 60, 65]
  lr_gamma: 0.5

  lr_milestones_multi: [1, 3, 5, 7]

  resume: false
  ckpt: log/HEM_main_1024_v1/version_1/checkpoints/epoch=9-step=161530.ckpt


datasets:
  vimeo90k:
    root: ../../vimeo_septuplet
    split_file: sep_trainlist.txt

    split_file_test: sep_testlist.txt


