name: EVC_main
version: 0.1

training:
  train_lambda: 0.03
  base_lr: 0.0001

  batch_size: 8

  q_index: 2



datasets:
  vimeo90k:
    root: D:/vimeo_septuplet
    split_file: sep_trainlist.txt
  
